// Builds icons.css: the Font Awesome icons this app actually uses, self-hosted.
//
// Gatekeeper handles wallet descriptors that must never leave the browser, so
// it loads no third-party code (issue #27). Rather than ship the Font Awesome
// webfonts, each icon is its SVG path drawn through a CSS mask, embedded as a
// data: URI so the page also works when opened from file:// (masks loaded from
// separate files are CORS-fetched and fail there).
//
// Icons are discovered by scanning the sources for "fa-<style> fa-<name>", so
// using a new icon only needs a rebuild: npm run build.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const FA = path.dirname(
  require.resolve("@fortawesome/fontawesome-free/package.json"),
);
const { version } = require("@fortawesome/fontawesome-free/package.json");

const SOURCES = ["index.html", "bitcoin-utils.js", "modules"];

const listFiles = (entry) => {
  const full = path.join(ROOT, entry);
  return fs.statSync(full).isDirectory()
    ? fs.readdirSync(full).map((f) => path.join(full, f))
    : [full];
};

const icons = new Map();
for (const file of SOURCES.flatMap(listFiles)) {
  const text = fs.readFileSync(file, "utf8");
  for (const [, style, name] of text.matchAll(
    /\bfa-(solid|regular|brands)\s+fa-([a-z0-9-]+)/g,
  )) {
    icons.set(`${style}/${name}`, { style, name });
  }
}

const rules = [...icons.values()]
  .sort((a, b) => `${a.style}/${a.name}`.localeCompare(`${b.style}/${b.name}`))
  .map(({ style, name }) => {
    const svg = fs
      .readFileSync(path.join(FA, "svgs", style, `${name}.svg`), "utf8")
      .replace(/<!--[\s\S]*?-->/g, "")
      .trim();
    const [, , w, h] = svg
      .match(/viewBox="([^"]+)"/)[1]
      .split(/\s+/)
      .map(Number);
    const width = +(w / h).toFixed(4);
    const uri = `data:image/svg+xml,${encodeURIComponent(svg)}`;
    return `.fa-${style}.fa-${name} {\n  --fa-icon: url("${uri}");\n  width: ${width}em;\n}`;
  });

const css = `/* Generated by scripts/build-icons.js — do not edit by hand.
 * Font Awesome Free ${version} by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0)
 * Copyright 2024 Fonticons, Inc. */

.fa-solid,
.fa-regular,
.fa-brands {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--fa-icon) center / contain no-repeat;
  mask: var(--fa-icon) center / contain no-repeat;
}

${rules.join("\n\n")}
`;

fs.writeFileSync(path.join(ROOT, "icons.css"), css);
console.log(`icons.css: ${icons.size} icons from Font Awesome Free ${version}`);
